### ISSUE TITLE
crash startup mod

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#1]
[latest.log](https://github.com/min2222/MCMTForge/files/14477916/latest.log)

**Comment by kitovoi111** [comment]
[debug.log](https://github.com/min2222/MCMTForge/files/14477918/debug.log)

**Comment by min2222** [comment]
working on fix, be patient

**Comment by kitovoi111** [comment]
thanks a lot.

**Comment by min2222** [comment]
updated latest release, just redownload it
