### ISSUE TITLE
[BUG] Error in console

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#1]
It gives a lot of errors in the console

[latest.log](https://github.com/min2222/MCMTForge/files/14484393/latest.log)
[debug.log](https://github.com/min2222/MCMTForge/files/14484394/debug.log)

**Comment by min2222** [comment]
you can ignore you are missing "" this may bite you later
but [MCMT-Pool-Thread-3/ERROR] [net.minecraft.util.ThreadingDetector/]: Thread dumps: is probably fixed in new release

**Comment by kitovoi111** [comment]
ok bro
