### ISSUE TITLE
TPS = 0, ticking block spam console (tube in IC2)

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#10]
no logs , only error in console spam and 0 tps in server very lagged.

![image](https://github.com/min2222/MCMTForge/assets/147491823/3b8e22ad-fe50-41fb-ac65-e4c9db54b710)
![image](https://github.com/min2222/MCMTForge/assets/147491823/28827bda-286b-44b5-86a3-2937bfb49d5e)

**Comment by min2222** [comment]
dupe #7
