### ISSUE TITLE
:D server crash ticking block

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#13]
[latest.log](https://github.com/min2222/MCMTForge/files/14561164/latest.log)

[crash-2024-03-11_18.55.57-server.txt](https://github.com/min2222/MCMTForge/files/14561165/crash-2024-03-11_18.55.57-server.txt)

[debug.log](https://github.com/min2222/MCMTForge/files/14561166/debug.log)

**Comment by kitovoi111** [comment]
and + crash
[crash-2024-03-11_18.57.44-server.txt](https://github.com/min2222/MCMTForge/files/14561184/crash-2024-03-11_18.57.44-server.txt)

**Comment by min2222** [comment]
issue of ic2 itself

**Comment by kitovoi111** [comment]
How can you disable multithreading on blocks from IC2? It’s just that the mod doesn’t have the source code, so it’s unlikely to be fixed. But there is an API, but I don't know how to use it.

**Comment by kitovoi111** [comment]
I just have the server itself on IC2 classic as the main mod so there is no way to delete it
