### ISSUE TITLE
Neruina error log spam in console

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#16]
![image](https://github.com/min2222/MCMTForge/assets/147491823/5aab0227-df57-4264-a0ea-98b4041c76d3)

**Comment by kitovoi111** [comment]
[debug.log](https://github.com/min2222/MCMTForge/files/14586538/debug.log)
[latest.log](https://github.com/min2222/MCMTForge/files/14586539/latest.log)

**Comment by kitovoi111** [comment]
mod: https://legacy.curseforge.com/minecraft/mc-mods/neruina

**Comment by min2222** [comment]
dupe #19
