### ISSUE TITLE
Error log in console (Open Parties and Claim mod & MoreMobGrifiengOptions)

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#18]
![image](https://github.com/min2222/MCMTForge/assets/147491823/066accdc-72d0-4a67-a3f3-32c77aadf4d4)
[debug.log](https://github.com/min2222/MCMTForge/files/14586921/debug.log)
[latest.log](https://github.com/min2222/MCMTForge/files/14586922/latest.log)

Mod: https://legacy.curseforge.com/minecraft/mc-mods/open-parties-and-claims
Mod: https://modrinth.com/mod/more-mobgriefing-options

**Comment by min2222** [comment]
dupe #15
