### ISSUE TITLE
After starting the server, it dies and does not respond

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#2]
1. Start server.. generate new map..
2. Stop server.
3. Repeat start server... waiting starting... R.I.P.
[crash-2024-03-04_10.55.08-server.txt](https://github.com/min2222/MCMTForge/files/14478203/crash-2024-03-04_10.55.08-server.txt)
[latest.log](https://github.com/min2222/MCMTForge/files/14478206/latest.log)
[debug.log](https://github.com/min2222/MCMTForge/files/14478207/debug.log)

**Comment by kitovoi111** [comment]
Problem in redstone

i changed in **server.properties** this value
**max-chained-neighbor-updates=0**
and my console:
and server R.I.P.
![image](https://github.com/min2222/MCMTForge/assets/147491823/22ccbff7-150f-44b2-886d-c29dd63775ab)

**Comment by kitovoi111** [comment]
and Threading Detector
[latest.log](https://github.com/min2222/MCMTForge/files/14478668/latest.log)

**Comment by min2222** [comment]
try with new version (just redownload 1.19.2-1)

**Comment by kitovoi111** [comment]
> try with new version (just redownload 1.19.2-1)

ok

**Comment by kitovoi111** [comment]
If an error appears, I will open the topic again.
