### ISSUE TITLE
[BUG] MCMT world threading bug (IC2 Classic)

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#2]
There was no such bug before, watch the video: https://youtu.be/R01xWJ9l6NI
command: /mcmt config toggle world

Wires do not connect, solar panels do not show that they are under the sun and other less interesting bugs.

**Comment by kitovoi111** [comment]
It seems to me that before this the port was better, there were fewer bugs, even nuclear reactors don’t work here. But some mods do not crash, for example the Flan mod works.

**Comment by kitovoi111** [comment]
Now I compared the new port and the old one that was there before. The old one turned out to be better, it just needs to fix some errors and it is perfect, I think we need to return the old port.

**Comment by min2222** [comment]
disable chunkLockModded in config will solve it

**Comment by kitovoi111** [comment]
Okay. I disable **chunkLockModded: false** in config , and problem no fixed. 
![image](https://github.com/min2222/MCMTForge/assets/147491823/7ae5bb76-bd97-419a-99a9-b4a7a64ee15b)

**Comment by kitovoi111** [comment]
![image](https://github.com/min2222/MCMTForge/assets/147491823/6adc40c2-b09d-4b8f-af8d-7f24f39f9bf8)

Disabling the multi-thread of the world helps, but thereby we lose the meaning of optimization. There was no such problem on the old version. (this https://github.com/himekifee/MCMTFabric)

**Comment by kitovoi111** [comment]
The pick-up (obsidian pipe) also causes the server to crash. I checked the old version of MCMT that you did yesterday - there is no crash. Everything works stably.
