### ISSUE TITLE
How do you know to make port SyncFuTransformer to forge ?

### ISSUE THREAD

**Issue by coco875** [min2222/MCMTForge#26]
I tried to make a multiloader version but encouter multiple problem and one are SyncFuTransformer so I was suprise when I see you manage to get it port this part and develope the mod even more. So I just wonder how you can get debug it and be able to know about ITransformer.
[the multiloader](https://github.com/coco875/MCMTFabric/tree/1.19)

**Comment by min2222** [comment]
unfortunately i don't have any knowledge about ITransformer, i just copy-pasted it from [here](https://github.com/jediminer543/JMT-MCMT/tree/1.18-master/sync-fu)

**Comment by coco875** [comment]
and this version are not better because more recent ? [here](https://github.com/jediminer543/JMT-MCMT/tree/master/src/syncfu)

**Comment by coco875** [comment]
Ok i manage to get it work
