### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#27]
[latest.log](https://github.com/min2222/MCMTForge/files/14623166/latest.log)
[debug.log](https://github.com/min2222/MCMTForge/files/14623168/debug.log)

**Comment by min2222** [comment]
disable mixin.collections.entity_by_type in canary

**Comment by kitovoi111** [comment]
> disable mixin.collections.entity_by_type in canary

i delete mod Canary and in console: https://pastebin.com/w5jLV0Ve
