### ISSUE TITLE
server freezing and crashing when i teleport in player home (schematic cannon loading schematic) or Huskyhomes in log

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#29]
[crash-2024-03-16_14.55.13-server.txt](https://github.com/min2222/MCMTForge/files/14623426/crash-2024-03-16_14.55.13-server.txt)
[latest.log](https://github.com/min2222/MCMTForge/files/14623427/latest.log)
[debug.log](https://github.com/min2222/MCMTForge/files/14623428/debug.log)

**Comment by min2222** [comment]
dupe #30
