### ISSUE TITLE
Redstone mechanisms do not work and crash the server

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#3]
Redstone mechanisms do not work and crash the server

1. Place redstone
2. I tried to activate it
3. Server R.I.P.
[latest.log](https://github.com/min2222/MCMTForge/files/14478239/latest.log)
[debug.log](https://github.com/min2222/MCMTForge/files/14478240/debug.log)

**Comment by min2222** [comment]
fixed
