### ISSUE TITLE
canary crashing server in startup

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#30]
in **canary.properties**
```
mixin.world.chunk_access=false
disable mixin.collections.entity_by_type=false
```

[crash-2024-03-16_14.58.30-server.txt](https://github.com/min2222/MCMTForge/files/14623435/crash-2024-03-16_14.58.30-server.txt)
[latest.log](https://github.com/min2222/MCMTForge/files/14623436/latest.log)
[debug.log](https://github.com/min2222/MCMTForge/files/14623437/debug.log)

**Comment by min2222** [comment]
https://www.reddit.com/r/admincraft/comments/wp3r87/serverhangwatchdog_detected_that_a_single_server/
