### ISSUE TITLE
crash server when in teleport VIDEO+LOGS+CRASH

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#31]
video: https://youtu.be/AAhAlN5RNVE 
[crash-2024-03-16_15.21.19-server.txt](https://github.com/min2222/MCMTForge/files/14623555/crash-2024-03-16_15.21.19-server.txt)
[latest.log](https://github.com/min2222/MCMTForge/files/14623556/latest.log)
[debug.log](https://github.com/min2222/MCMTForge/files/14623557/debug.log)

**Comment by min2222** [comment]
#30
