### ISSUE TITLE
Mod Canary no working.

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#32]
No working.

mixin.world.chunk_access=false
disable mixin.collections.entity_by_type=false

Server after starting freezing and crashing.

**Comment by min2222** [comment]
remove word disable

mixin.world.chunk_access=false
mixin.collections.entity_by_type=false

**Comment by kitovoi111** [comment]
[latest.log](https://github.com/min2222/MCMTForge/files/14626432/latest.log)
[debug.log](https://github.com/min2222/MCMTForge/files/14626433/debug.log)

**Comment by kitovoi111** [comment]
@min2222 

Please don’t delete the message, let’s discuss this quietly here. I have a problem with Alex's Caves 1.1.4 that you uploaded, where if you tame a dinosaur, it cannot fly, and also the shaker does not walk correctly when you saddle it. There is also a client crash.
[crash-2024-03-29_23.47.50-client.txt](https://github.com/min2222/MCMTForge/files/14817929/crash-2024-03-29_23.47.50-client.txt)
I'm willing to pay for fixes, send your Tether TRC20 wallet

**Comment by min2222** [comment]
> @min2222
> 
> Please don’t delete the message, let’s discuss this quietly here. I have a problem with Alex's Caves 1.1.4 that you uploaded, where if you tame a dinosaur, it cannot fly, and also the shaker does not walk correctly when you saddle it. There is also a client crash. [crash-2024-03-29_23.47.50-client.txt](https://github.com/min2222/MCMTForge/files/14817929/crash-2024-03-29_23.47.50-client.txt) I'm willing to pay for fixes, send your Tether TRC20 wallet

https://www.mediafire.com/file/t4w47vs0q9mq1je/alexscaves-1.1.4.jar/file
to me, there is no problem

**Comment by kitovoi111** [comment]
> > @min2222
> > Please don’t delete the message, let’s discuss this quietly here. I have a problem with Alex's Caves 1.1.4 that you uploaded, where if you tame a dinosaur, it cannot fly, and also the shaker does not walk correctly when you saddle it. There is also a client crash. [crash-2024-03-29_23.47.50-client.txt](https://github.com/min2222/MCMTForge/files/14817929/crash-2024-03-29_23.47.50-client.txt) I'm willing to pay for fixes, send your Tether TRC20 wallet
> 
> https://www.mediafire.com/file/t4w47vs0q9mq1je/alexscaves-1.1.4.jar/file to me, there is no problem

Thanks a lot! I'll check!

**Comment by kitovoi111** [comment]
![image](https://github.com/min2222/MCMTForge/assets/147491823/a0570c75-bd00-4cea-89c1-10ad153b9d95)
![image](https://github.com/min2222/MCMTForge/assets/147491823/c50549b6-bca3-4e3e-9153-8bbfb07c5348)
![image](https://github.com/min2222/MCMTForge/assets/147491823/5c845afc-96cf-44a8-97ec-67bcae3d0ab6)

**Comment by kitovoi111** [comment]
![image](https://github.com/min2222/MCMTForge/assets/147491823/0b24c1e2-3036-456a-b675-6811858a9490)

**Comment by kitovoi111** [comment]
Hello my friend. I don’t understand why you deleted the screenshots, but in Alex’s Caves the one you sent me has a problem with a dinosaur, it stands 1 block above the ground.

**Comment by kitovoi111** [comment]
![image](https://github.com/min2222/MCMTForge/assets/147491823/c1241050-5373-4c41-83a1-06eef45adc0e)

And the question is, is it normal for so many of them to spawn?

**Comment by min2222** [comment]
> Hello my friend. I don’t understand why you deleted the screenshots, but in Alex’s Caves the one you sent me has a problem with a dinosaur, it stands 1 block above the ground.
> 
> ![image](https://private-user-images.githubusercontent.com/147491823/319973205-639c50ab-b0c6-4bb1-94cf-8a939fc76c35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjQ3MDEsIm5iZiI6MTcxMjMyNDQwMSwicGF0aCI6Ii8xNDc0OTE4MjMvMzE5OTczMjA1LTYzOWM1MGFiLWIwYzYtNGJiMS05NGNmLThhOTM5ZmM3NmMzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxMzQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTA2NjA0NjQ3ODI1MTdiMTYzZTRjYjY0NDBlOWJjMmMwZjFhNTk2ZTI4YjFiMmZkZmVmYjdlYjRiYzA0MTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IIkrzJPDqwQpJlE0kYGXgVn5V7_T0cppA-SnX_DoKnc)

https://www.mediafire.com/file/ua74aboy1kpj3va/alexscaves-1.1.4.jar/file

**Comment by kitovoi111** [comment]
Hi bro. https://github.com/AlexModGuy/AlexsCaves/issues/1020#issuecomment-2071904606 this really fix in alex's caves?

**Comment by kitovoi111** [comment]
[crash-2024-03-29_23.47.50-client (2).txt](https://github.com/min2222/MCMTForge/files/15083668/crash-2024-03-29_23.47.50-client.2.txt)

**Comment by kitovoi111** [comment]
Help please bro.

**Comment by kitovoi111** [comment]
[crash-2024-03-29_23.47.50-client.2.txt](https://github.com/min2222/MCMTForge/files/15138169/crash-2024-03-29_23.47.50-client.2.txt)

**Comment by kitovoi111** [comment]
@min2222 help bro please..
