### ISSUE TITLE
[BUG] teBlackList does not work correctly and crash server

### ISSUE THREAD

**Issue by kitovoi111** [min2222/MCMTForge#4]
**teBlackList = ["ic2.core.entity.misc.MiningLaserEntity"]** does not work
my server crashing, when I shooting the mining laser. in the Console it says add this ID to the blacklist. I add - it doesn't help.
log: [2024-03-05-2.log](https://github.com/min2222/MCMTForge/files/14492292/2024-03-05-2.log)

**Comment by min2222** [comment]
te means tile entity, aka block entity.

**Comment by kitovoi111** [comment]
I can't find the blacklist of blocks. Only teBlackList

**Comment by min2222** [comment]
currently working on fix

**Comment by kitovoi111** [comment]
Thank you very much for your work. You are a coding guru.
